blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Request Help
    url: https://github.com/insanity54/slvtt/discussions
    about: Please use Discussions for questions or usage help.
